### ISSUE TITLE
License

### ISSUE THREAD

**Issue by reifnir** [reinoudk/terraform-provider-toggles#2]
Hi there, I don't see what license you're applying to this software. Is that something you could add?

**Comment by reinoudk** [comment]
Hi @reifnir, thanks for noticing. It was mostly something to experiment with so I didn't add a license yet. I've now added the MIT license (41629043103b2cac1871cfd548edc9a67cb40856). The previous change was 7 months ago and now the acceptance test seems to be broken. I might look into that next week, but I'm not actively using the `toggles` provider at the moment.

**Comment by reifnir** [comment]
That's great! Thanks!
