### ISSUE TITLE
PGP key expired

### ISSUE THREAD

**Issue by bryceml** [reinoudk/terraform-provider-toggles#3]
╷
│ Error: Failed to install provider
│ 
│ Error while installing reinoudk/toggles v0.3.0: error checking signature:
│ openpgp: key expired
╵

**Comment by bryceml** [comment]
This appears to be fixed on mac by upgrading to terraform 1.6.1, see related issues:

https://github.com/hashicorp/terraform/releases/tag/v1.6.1

cli: Reverted back to previous behavior of ignoring signing key expiration for provider installation, since it's the provider registry's responsibility to verify key validity at publication time. [https://github.com/hashicorp/terraform/pull/34004]

**Comment by reinoudk** [comment]
Glad it got resolved @bryceml, thanks for updating the issue. It's a good reminder though to update my GPG keys. 
To be honest, I wasn't aware this provider was actually used 😅 .
